[server]
port = ":11451"
debug = true
prefork = false

[server.tls]
enable = false
cert_file = "cert.pem"
key_file = "key.pem"

[server.cors]
enable = true

[server.jwt]
secret = "data_horader"


[database]
type = "sqlite3"
port = 0
db_file = "data_horader.db"
table_prefix = "sg_"
migrate = true

[logger]
log_level = "debug"
log_path = "logs"
log_name = "data_horader"
log_ext = "log"
